apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-west-2
  tags:
    karpenter.sh/discovery: demo-cluster

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true
  - name: ng-2
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      publicKeyPath: 
